[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C", "link-args=-fuse-ld=/usr/bin/mold",
# (Nightly) Make the current crate share its generic instantiations
    "-Zshare-generics=y",
]

